### ISSUE TITLE
Uncaught RangeError: Offset is outside the bounds of the DataView, when reading a specific JPEG file

### ISSUE THREAD

**Issue by Jarzka** [remvee/cljs-exif-reader#2]
**Problem:**
It seems that when I try to read exif data for a specific JPEG image, I get an error "Offset is outside the bounds of the DataView".

**Expected output**
The exif data of the image should be read and I believe the exif-reader should never crash.

**How to reproduce:**
Download the JPEG image which causes this:
_removed_

I use `(js/FileReader.)` to read the image, then read the `(.-result reader)` property out of it, and finally I call `(exif-reader/from-jpeg result)`.

**Version used:**
`[remworks/cljs-exif-reader "0.2.0" :exclusions [com.google.guava/guava]]`

**Full console output:**
`
Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at Object.remworks$data_view$IDataView$getUint32$arity$3 (data_view.cljc:66)
    at remworks$data_view$getUint32 (data_view.cljc:9)
    at remworks$exif_reader$ifds (exif_reader.cljc:300)
    at exif_reader.cljc:304
    at exif_reader.cljc:305
    at Object.sval (core.cljs:3399)
    at Object.cljs$core$ISeqable$_seq$arity$1 (core.cljs:3453)
    at Object.cljs$core$seq [as seq] (core.cljs:1210)
    at core.cljs:4676
  | (anonymous) | @ | data_view.cljc:66
-- | -- | -- | --
  | remworks$data_view$getUint32 | @ | data_view.cljc:9
  | remworks$exif_reader$ifds | @ | exif_reader.cljc:300
  | (anonymous) | @ | exif_reader.cljc:304
  | (anonymous) | @ | exif_reader.cljc:305
  | (anonymous) | @ | core.cljs:3399
  | (anonymous) | @ | core.cljs:3453
  | cljs$core$seq | @ | core.cljs:1210
  | (anonymous) | @ | core.cljs:4676
  | (anonymous) | @ | core.cljs:3399
  | (anonymous) | @ | core.cljs:3453
  | cljs$core$seq | @ | core.cljs:1210
  | (anonymous) | @ | core.cljs:3232
  | cljs$core$next | @ | core.cljs:1255
  | (anonymous) | @ | core.cljs:3765
  | (anonymous) | @ | core.cljs:3399
  | (anonymous) | @ | core.cljs:3453
  | cljs$core$seq | @ | core.cljs:1210
  | (anonymous) | @ | core.cljs:5118
  | (anonymous) | @ | core.cljs:3399
  | (anonymous) | @ | core.cljs:3453
  | cljs$core$seq | @ | core.cljs:1210
  | (anonymous) | @ | core.cljs:5118
  | (anonymous) | @ | core.cljs:3399
  | (anonymous) | @ | core.cljs:3453
  | cljs$core$seq | @ | core.cljs:1210
  | (anonymous) | @ | core.cljs:3749
  | (anonymous) | @ | core.cljs:3399
  | (anonymous) | @ | core.cljs:3453
  | cljs$core$seq | @ | core.cljs:1210
  | (anonymous) | @ | core.cljs:3232
  | cljs$core$next | @ | core.cljs:1255
  | (anonymous) | @ | core.cljs:2455
  | (anonymous) | @ | core.cljs:3463
  | (anonymous) | @ | core.cljs:2522
  | cljs$core$reduce | @ | core.cljs:2490
  | remworks$exif_reader$from_tiff | @ | exif_reader.cljc:322
  | remworks$exif_reader$from_jpeg | @ | exif_reader.cljc:351
  | (anonymous) | @ | exif_lukupalvelu.cljs:33
  | trex$palvelut$liitteet$exif_lukupalvelu$lue_kuvan_exif_tiedot | @ | exif_lukupalvelu.cljs:34
  | (anonymous) | @ | liitejonopalvelu.cljs:145
  | FileReader (async) |   |  
  | trex$palvelut$liitteet$liitejonopalvelu$kasittele_kuvan_upload_BANG_ | @ | liitejonopalvelu.cljs:154
  | (anonymous) | @ | std_interceptors.cljc:115
  | re_frame$std_interceptors$db_handler__GT_interceptor_$_db_handler_before | @ | std_interceptors.cljc:111
  | re_frame$interceptor$invoke_interceptor_fn | @ | interceptor.cljc:68
  | re_frame$interceptor$invoke_interceptors | @ | interceptor.cljc:106
  | re_frame$interceptor$execute | @ | interceptor.cljc:199
  | re_frame$events$handle | @ | events.cljc:65
  | (anonymous) | @ | router.cljc:179
  | re_frame$router$_process_1st_event_in_queue | @ | router.cljc:84
  | (anonymous) | @ | router.cljc:198
  | re_frame$router$_run_queue | @ | router.cljc:86
  | (anonymous) | @ | router.cljc:146
  | (anonymous) | @ | router.cljc:169
  | re_frame$router$_fsm_trigger | @ | router.cljc:80
  | (anonymous) | @ | router.cljc:187
  | channel.port1.onmessage | @ | nexttick.js:211

`

**Comment by remvee** [comment]
Thanks for the report.  Can I use the metadata for the image for the test suite?  I'll be running something like `convert your-image.jpg -scale 1x1 malformed.jpg` using imagemagick to strip the actual image, but the metadata (including a preview image) will stay intact.  We'll probably will need consent from Matti Piispanen because the metadata states he's the owner of the image.

**Comment by remvee** [comment]
This is the only image I got displaying these particular symptoms; the GPS information is corrupted which makes the code derail.  I can paste over his name (and email address, which is also in the metadata) using a binary editor.

**Comment by remvee** [comment]
Oh, and phone number.. Ieks..

**Comment by remvee** [comment]
@Jarzka please remove the image from dropbox, I have a local copy.

**Comment by Jarzka** [comment]
Good, this makes the meta data "unique" and testable.

I removed the image from my Dropbox.

**Comment by remvee** [comment]
Fix in commit 4f67f7434a807840f81d6022ac3bceb1bbc716ee, deployed a new release 0.3.0 to clojars.

**Comment by Jarzka** [comment]
Thanks for fixing this so quickly. Seems not to crash anymore. 👍
